# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches:
      - main

jobs:
  BACKEND:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:  
          branch: main
          appdir: ./backend
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nsbm-spm-backend" #Must be unique in Heroku
          heroku_email: "dehemisandeepani@gmail.com"
  USER:
   needs: BACKEND
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:  
          branch: main
          appdir: ./frontend/frontend
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nsbm-spm-user" #Must be unique in Heroku
          heroku_email: "dehemisandeepani@gmail.com"
  ADMIN:
    needs: USER
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:  
          branch: main
          appdir: ./admin/admin
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nsbm-spm-admin" #Must be unique in Heroku
          heroku_email: "dehemisandeepani@gmail.com"
